# Generated by Django 3.2.6 on 2021-08-17 17:18

from django.db import migrations, models
import music.validators


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(upload_to='musics', validators=[music.validators.validate_audio]),
        ),
    ]
