# Generated by Django 3.2.6 on 2021-08-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='album/cover_images/'),
        ),
    ]
